<a href="https://colab.research.google.com/github/adambartlettds/Farm-Animal-Image-Classifier/blob/main/double_vs_single_brackets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({"product_id": [0,1,2,3,4], "low_fats" : ['Y','Y','N','Y','N'], "recyclable" : ['N','Y','Y','Y','N']})

In [ ]:
df.head()

product_id low_fats recyclable
0           0        Y          N
1           1        Y          Y
2           2        N          Y
3           3        Y          Y
4           4        N          N

In [ ]:
df['product_id']

0    0
1    1
2    2
3    3
4    4
Name: product_id, dtype: int64

In [ ]:
df[['product_id']]


product_id
0           0
1           1
2           2
3           3
4           4

In [ ]:
df['product_id']

0    0
1    1
2    2
3    3
4    4
Name: product_id, dtype: int64

In [ ]:
print(df['product_id'])

0    0
1    1
2    2
3    3
4    4
Name: product_id, dtype: int64


In [ ]:
print(df[['product_id']])

   product_id
0           0
1           1
2           2
3           3
4           4


In [ ]:
np.array(df['product_id'])

array([0, 1, 2, 3, 4])

In [ ]:
np.array(df[['productid']])

KeyError: ignored

In [ ]:
pd.Series([[0],
       [1],
       [2],
       [3],
       [4]])

0    [0]
1    [1]
2    [2]
3    [3]
4    [4]
dtype: object

In [ ]:
list = [1,2,3,4,5]

In [ ]:
list[0] #normal indexing

1

In [ ]:
list[list[0]]

2

In [ ]:
 np.array()

In [ ]:
flat_array = np.array([0, 1, 2, 3, 4])


In [ ]:
not_flat_array = np.array(([[0],
       [1],
       [2],
       [3],
       [4]]))

In [ ]:
pd.Series(flat_array)

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [ ]:
pd.Series(not_flat_array)

ValueError: ignored

In [ ]:
pd.DataFrame(flat_array)

0
0  0
1  1
2  2
3  3
4  4

In [ ]:
pd.DataFrame(not_flat_array)

0
0  0
1  1
2  2
3  3
4  4

In [ ]:
two_dee_array = np.array(
      [[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [10, 11, 12, 13, 14]])

In [ ]:
two_dee_array[1]

array([5, 6, 7, 8, 9])

In [ ]:
two_dee_array[1].ndim

1

In [ ]:
two_dee_array[[1]]

array([[5, 6, 7, 8, 9]])

In [ ]:
two_dee_array[[1]].ndim

2

In [ ]:
df = pd.DataFrame(two_dee_array, columns=["0th", "1st", "2nd", "3rd", "4th"])

In [ ]:
df.head()

0th  1st  2nd  3rd  4th
0    0    1    2    3    4
1    5    6    7    8    9
2   10   11   12   13   14

In [ ]:
df.ndim

2

In [ ]:
df["0th"].ndim

1

In [ ]:
df[["0th"]].ndim

2

In [ ]:
two_dee_array_t = np.transpose(two_dee_array)

In [ ]:
two_dee_array_t

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
big_box = pd.DataFrame(two_dee_array_t, columns=["plates", "silverware", "glassware"])

In [ ]:
big_box

plates  silverware  glassware
0       0           5         10
1       1           6         11
2       2           7         12
3       3           8         13
4       4           9         14

In [ ]:
big_box['plates']

0    0
1    1
2    2
3    3
4    4
Name: plates, dtype: int64

In [ ]:
big_box[['plates']]

plates
0       0
1       1
2       2
3       3
4       4